# Generated by Django 4.2 on 2023-04-15 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0004_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
