# Generated by Django 4.2 on 2023-04-15 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0005_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='pay_for_study',
            field=models.BooleanField(default=True),
        ),
    ]
