# Generated by Django 4.2 on 2023-04-16 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0006_student_pay_for_study'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='hour_need',
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AddField(
            model_name='student',
            name='study_week_need',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='student',
            name='subject_need',
            field=models.PositiveIntegerField(default=8),
        ),
    ]
